name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  bloc: ^9.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  auto_route: ^11.1.0
  retrofit: ^4.9.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.11.3
  build_runner: ^2.4.15
  auto_route_generator: ^10.4.0
  retrofit_generator: ^10.2.1

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

